name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true

jobs:

  bump-version:
    uses: diamcircle/actions/.github/workflows/rust-bump-version.yml@main
    with:
      version: ${{ inputs.version }}
